### ISSUE TITLE
Allow running any Python command when stopped at a breakpoint

### ISSUE THREAD

**Issue by lassoan** [jupyter-xeus/xeus-python#276]
Having the ability to do line-by-line debugging in Jupyterlab will be very useful!

Unfortunately, I cannot really use this for real work yet, as an essential feature is missing: being able to run any command while the debugger is stopped at a breakpoint.

This feature is needed to be able to debug in long iterations, inspect and change any variables, and experiment with running arbitrary methods in that context.

**Comment by JohanMabille** [comment]
`xeus-python` supports the DAP protocol, which provides a request to execute code when the interpreter is stopped on a breakpoint. So I think this requires development in Jupyter Lab rather than in `xeus-python` (except for the bugs we may find when starting to test and use this feature;)).

cc @jtpio @afshin

**Comment by jtpio** [comment]
Yes, it's being tracked in https://github.com/jupyterlab/debugger/issues/409 and https://github.com/jupyterlab/debugger/issues/419.

**Comment by SylvainCorlay** [comment]
Yep, thanks @lassoan! Closing this issue since this is more related to the front-end.
