### ISSUE TITLE
Allow for a console at breakpoint

### ISSUE THREAD

**Issue by LucaMarconato** [jupyter-xeus/xeus-python#423]
One of the features that I like the most about Python debuggers (like in PyCharm), is that you can open a Python console in the breakpoint and execute new commands with the variable values at the point in which the execution stopped. I have tried xeus-python and I couldn't find this feature.

Is it already available? If not, please consider adding that, since it would improved the power of the debugger.

**Comment by gwtaylor** [comment]
I would love to see this feature as well. I note that you can open a xeus-python console via "File -> New Console for Notebook" and this works great. But once you enter debugging, this console is "frozen" until debugging stops. Then the console is back to global scope (rather than the scope within the debugger). It would be wonderful if you could interactively work with the state of the program during debugging from the console.

**Comment by JohanMabille** [comment]
> Is it already available?

Wihle the backend already supports executing code when stopped on a breakpoint, the GUI to do so has not been implemented in the frontend yet. This issue should be open on the [JupyterLab repo](https://github.com/jupyterlab/jupyterlab/issues).
