### ISSUE TITLE
Mix using Python and Javascript in Xeus just like in Pyodide

### ISSUE THREAD

**Issue by MRYingLEE** [jupyter-xeus/xeus-python#591]
It is said "Pyodide comes with a robust Javascript ⟺ Python foreign function interface so that you can freely mix these two languages in your code with minimal friction. " at https://pyodide.org/en/stable/ .

I am just wondering whether xeus-python has similar feature.

Please clarify. 

Thank you in advance,

**Comment by JohanMabille** [comment]
Hi,

xeus-python is a Python only kernel, it does not provide such a feature.

**Comment by martinRenou** [comment]
I suspect you wanted to open this issue to jupyterlite-xeus-python. We do provide similar APIs through the emscripten forge's pyjs library. @DerThorsten can probably tell how much of the JavaScript standard API is exposed. 

Note that because the jupyterlite kernel is running in a web worker, it does not have access to DOM APIs, the pyodide kernel has the same limitation.

**Comment by martinRenou** [comment]
https://github.com/emscripten-forge/pyjs
